# Form implementation generated from reading ui file '/media/miles/Commun/Studi/0_2_Evaluations/ECF/PARADOX-EG/desktop/gui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("background-color: #1e1e1e;\n"
"    color: #b8b8b8;\n"
"    font-family: Arial;")
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bookingList = QtWidgets.QListWidget(parent=MainWindow)
        self.bookingList.setStyleSheet("background-color: #1e1e1e;\n"
"       color: #b8b8b8;\n"
"       font-family: Arial;\n"
"       selection-background-color: #3A3238;\n"
"       selection-color: #b8b8b8;")
        self.bookingList.setObjectName("bookingList")
        self.verticalLayout.addWidget(self.bookingList)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Booking List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
