# Generated by Django 4.1.2 on 2023-01-14 23:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='No description available.', max_length=1000)),
                ('duration', models.DurationField(default='01:00:00')),
                ('difficulty', models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Normal'), (4, 'Hard'), (5, 'Very Hard')])),
                ('min_players', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_players', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('scenery', models.ImageField(default=None, upload_to='pegapp/uploads/images/scenery/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegapp.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pegapp/uploads/images/gallery/')),
                ('name', models.CharField(default='No Name Image', max_length=20)),
                ('scenario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegapp.scenario')),
            ],
        ),
    ]
