# Generated by Django 4.1.2 on 2022-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='duration',
            field=models.DurationField(default='01:00:00'),
        ),
    ]
