# Generated by Django 4.1.2 on 2022-10-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_path',
            new_name='image',
        ),
        migrations.AddField(
            model_name='scenario',
            name='images',
            field=models.ManyToManyField(to='pegapp.image'),
        ),
    ]
