# Generated by Django 4.1.2 on 2022-10-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0004_rename_img_path_image_image_scenario_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pegapp/uploads/images/gallery/'),
        ),
    ]
