# Generated by Django 4.1.2 on 2022-10-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='max_players',
            field=models.IntegerField(default=5, max_length=10),
        ),
        migrations.AddField(
            model_name='scenario',
            name='min_players',
            field=models.IntegerField(default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(default='No description available.', max_length=1000),
        ),
    ]
