# Generated by Django 4.1.2 on 2022-10-16 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0006_scenario_max_players_scenario_min_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='max_players',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='min_players',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
