# Generated by Django 4.1.2 on 2023-07-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0006_alter_scenario_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.JSONField(default=list)),
            ],
        ),
    ]
