# Generated by Django 4.1.2 on 2022-10-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0007_alter_scenario_max_players_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegapp.scenario')),
            ],
        ),
    ]
