# Generated by Django 4.1.2 on 2022-10-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0007_alter_scenario_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='images',
            field=models.ManyToManyField(null=True, to='pegapp.image'),
        ),
    ]
