# Generated by Django 4.1.2 on 2022-10-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0008_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='num',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
