# Generated by Django 4.1.2 on 2022-10-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0008_alter_scenario_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='images',
            field=models.ManyToManyField(blank=True, to='pegapp.image'),
        ),
    ]
