# Generated by Django 4.1.2 on 2022-10-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0009_alter_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
