# Generated by Django 4.1.2 on 2022-10-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0009_alter_scenario_images'),
        ('pegapp', '0010_alter_room_num'),
    ]

    operations = [
    ]
