# Generated by Django 4.1.2 on 2022-10-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0011_merge_0009_alter_scenario_images_0010_alter_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegapp.scenario'),
        ),
    ]
