# Generated by Django 4.1.2 on 2022-10-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0012_alter_room_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.CharField(choices=[('Principal', 'Pincipal'), ('Secondary', 'Secondary')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
