# Generated by Django 4.1.2 on 2022-12-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0013_image_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='images',
            new_name='gallery',
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenery',
            field=models.ImageField(default=None, upload_to='pegapp/uploads/images/scenery/'),
        ),
    ]
