# Generated by Django 4.1.2 on 2022-12-27 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0014_rename_images_scenario_gallery_scenario_scenery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='gallery',
        ),
        migrations.AddField(
            model_name='image',
            name='scenario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegapp.scenario'),
        ),
    ]
