# Generated by Django 4.1.2 on 2022-12-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0015_remove_image_priority_remove_scenario_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='No Name Image', max_length=20),
        ),
    ]
