# Generated by Django 4.1.2 on 2023-07-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0010_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5),
        ),
    ]
