# Generated by Django 4.1.2 on 2023-07-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0011_alter_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chrono',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='gameover_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
