# Generated by Django 4.1.2 on 2023-07-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0007_defaultpricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='DefaultPriceList',
        ),
    ]
