# Generated by Django 4.1.2 on 2023-07-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegapp', '0012_booking_chrono_booking_gameover_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chrono',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gameover_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
